name: Publish Python Package
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: false

on: 
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  publish_pypi:
    name: Publish to PyPi
    runs-on: ubuntu-20.04
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
      contents: write
    environment:
      name: pypi
      url: https://pypi.org/p/pyflasc
    steps:
      - name: Extract version
        id: version
        run: |
          TAG=${{ github.ref }}
          VERSION=${TAG#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=v$VERSION" >> $GITHUB_OUTPUT

      - name: Download wheels and sdist
        uses: dawidd6/action-download-artifact@v2.27.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: Tests.yml
          workflow_conclusion: success
          branch: main
          path: .
              
      - name: Move files to dist
        run: |
          mkdir dist
          mv dists/* dist/
          if [[ ! -f dist/lensed_umap-${{ steps.version.outputs.version }}.tar.gz ]] ; then exit 1; fi
      
      - name: Create Github Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        run: |
          gh release create -R vda-lab/lensed_umap -t "Version ${{ steps.version.outputs.version }}" -n "**Full Changelog**: https://github.com/vda-lab/lensed_umap/commits/${{ steps.version.outputs.tag }}" "${{ steps.version.outputs.tag }}" dist/*.whl dist/*.tar.gz
        
      - name: Publish package to (Test)PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.5
        # Comment lines below to publish to PyPi instead of test PyPi
        # with:
        #   repository-url: https://test.pypi.org/legacy/
